version: "3.8"
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./Frontend:/app
    ports:
      - "3001:3000"
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./Backend:/app
    ports:
      - "3002:3000"
  admin:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./Admin:/app
    ports:
      - "3003:3000"